### ISSUE TITLE
llcppsigfetch: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by tsingbx** [luoliwoshang/llgo#134]
run llcppsigfetch --extract filter.h will panic
[filter.h.zip](https://github.com/user-attachments/files/17698503/filter.h.zip)

**Comment by luoliwoshang** [comment]
这个llcppsymg.symb.json 是空的吗

**Comment by tsingbx** [comment]
因为注释里面的%字符导致
```c
* \code{.c}
 * const char *str = ...; // From user
 * lzma_filter filters[LZMA_FILTERS_MAX + 1];
 * int pos;
 * const char *msg = lzma_str_to_filters(str, &pos, filters, 0, NULL);
 * if (msg != NULL) {
 *     printf("%s: Error in XZ compression options:\n", argv[0]);
 *     printf("%s: %s\n", argv[0], str);
 *     printf("%s: %*s^\n", argv[0], errpos, "");
 *     printf("%s: %s\n", argv[0], msg);
```

**Comment by tsingbx** [comment]
%s，%d 都不行， %6就没有问题。这个应该是cjson本身的问题。

**Comment by luoliwoshang** [comment]
> %s，%d 都不行， %6就没有问题。这个应该是cjson本身的问题。

这里看看能不能加上转译什么的处理

**Comment by tsingbx** [comment]
c/cjson/_demo/mkjson/mkjson.go中 %s,%d，没有问题。

**Comment by tsingbx** [comment]
看起来好像是把注释里面的%d,%s这些东西当成格式字符串了，有的时候又不当成格式字符串如c/cjson/_demo/mkjson/mkjson.go，如果把%替换成%%，好像又没有问题，结果只有一个%，不会出现%%。原因不明。
