### ISSUE TITLE
llcppsigfetch:nil panic caused by access Name member of a nil ast.Ident

### ISSUE THREAD

**Issue by tsingbx** [luoliwoshang/llgo#97]
panic when convert a typedef under the case of typedef struct { a int; } XXX;  which hasn't struct name.
[__stddef_max_align_t.zip](https://github.com/user-attachments/files/17388470/__stddef_max_align_t.zip)

fix:#101

**Comment by luoliwoshang** [comment]
目前对于一个 typedef struct { a int; } XXX; 现在的 libclang 中实际上会认为他是存在两个节点，一个是匿名的节点 struct {a int; } 这个会生成一个匿名的Typedecl节点（即Name为nil的节点）另外一个节点即 typedef 节点，用于实际的typedef定义。

**Comment by luoliwoshang** [comment]
> 目前对于一个 typedef struct { a int; } XXX; 现在的 libclang 中实际上会认为他是存在两个节点，一个是匿名的节点 struct {a int; } 这个会生成一个匿名的Typedecl节点（即Name为nil的节点）另外一个节点即 typedef 节点，用于实际的typedef定义。

对于llcppsigfetch对应的匿名节点先我去做一个对应的识别
